# Site settings
title: Robert Rouhani
email: robert.rouhani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The homepage of Robert Rouhani
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robmaister.com" # the base hostname & protocol for your site

handles:
  twitter: robmaister
  facebook: robert.rouhani


# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/
timezone: America/New_York

social-media-links:
  - site: Github
    icon: fa-github
    url: https://github.com/Robmaister
  - site: Stack Overflow
    icon: fa-stack-overflow
    url: http://stackoverflow.com/users/1122135/robert-rouhani
  - site: Facebook
    icon: fa-facebook
    url: https://www.facebook.com/robert.rouhani
  - site: Twitter
    icon: fa-twitter
    url: https://twitter.com/robmaister
    
defaults:
  -
    scope:
      path: ""
    values:
      bg: bg-default.jpg