# Site settings
title: Robert Rouhani
email: robert.rouhani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The homepage of Robert Rouhani
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://robmaister.com" # the base hostname & protocol for your site

handles:
  twitter: robmaister
  facebook: robert.rouhani

permalink: /blog/:categories/:year/:month/:day/:title/
timezone: America/Los_Angeles

# Build settings
plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

paginate: 5
paginate_path: "/blog/page/:num/"

collections:
  blog_tags:
    output: true
    permalink: /blog/tag/:name/

social-media-links:
  - site: Github
    icon: fa-github
    url: https://github.com/Robmaister
  - site: Stack Overflow
    icon: fa-stack-overflow
    url: https://stackoverflow.com/users/1122135/robert-rouhani
    
defaults:
  -
    scope:
      path: ""
    values:
      bg: bg-default-min.jpg
  -
    scope:
      path: ""
      type: blog_tags
    values:
      layout: blog_tag